---


CLASH_CFG_DIR: "{{ COMMON_CFG_DIR }}/clash"
CLASH_COUNTRY_FILE: "{{ CLASH_CFG_DIR }}/Country.mmdb"
CLASH_BIN_FILE: "{{ COMMON_BIN_DIR }}/clash"
CLASH_SUBSCRIBES_FILE: "{{ CLASH_CFG_DIR }}/subscribes.txt"
CLASH_INITD_FILE: "{{ COMMON_INITD_DIR }}/S25clash"
CLASH_UPDATE_SUBSCRIBES_FILE: "{{ COMMON_BIN_DIR }}/update_subscribes"
CLASH_SWITCH_CONFIG_FILE: "{{ COMMON_BIN_DIR }}/switch_config"
CLASH_SUBSCRIBES: []
CLASH_REDIR_PORT: 7892
CLASH_DNS_PORT: 55
