---

- name: create config directory
  file:
    name: "{{ IPSET_CFG_DIR }}"
    state: directory
    mode: 0644

- name: setup script for update whitelist
  template:
    src: update_whitelist.py
    dest: "{{ IPSET_UPDATE_WHITELIST_FILE }}"
    mode: 0755

- name: copy preset china ip
  template:
    src: apnic.txt
    dest: "{{ IPSET_APNIC_FILE }}"
    mode: 0755

- name: setup bypass ip list
  template:
    src: whitelist.txt.j2
    dest: "{{ IPSET_WHITELIST_FILE }}"
    mode: 0644

- name: config cron for update ip whitelist
  command: 'cru a update_whitelist "0 2 * * * {{ IPSET_UPDATE_WHITELIST_FILE }}"'

- name: make sure cron worked after reboot
  lineinfile:
    line: 'cru a update_whitelist "0 2 * * * {{ IPSET_UPDATE_WHITELIST_FILE }}"'
    path: "{{ JFFS_WAN_START_FILE }}"

- name: update ip whitelist
  command: '{{ IPSET_UPDATE_WHITELIST_FILE }} skip'

