---

- name: setup update script
  template:
    src: adblock_update_rules.j2
    dest: "{{ADBLOCK_UPDATE_RULE_FILE}}"
    mode: 0755

- name: config cron for update
  command: "{{ADBLOCK_UPDATE_RULES_CRON_CMD}}"

- name: make sure cron worked after reboot
  lineinfile:
    line: "{{ADBLOCK_UPDATE_RULES_CRON_CMD}}"
    path: "{{JFFS_WAN_START_FILE}}"

- name: execute update
  command: "{{ADBLOCK_UPDATE_RULE_FILE}}"

- name: restart dnsmasq
  command: "{{DNSMASQ_INITD_FILE}} restart"
