---

- name: create config directory
  file:
    name: "{{ CLASH_CFG_DIR }}"
    state: directory
    mode: 0644

- name: clash config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - {src: subscribes.txt.j2, dest: "{{ CLASH_SUBSCRIBES_FILE }}", mode: 0644}
    - {src: S25clash.j2, dest: "{{ CLASH_INITD_FILE }}", mode: 0755}
    - {src: update_subscribes.py, dest: "{{ CLASH_UPDATE_SUBSCRIBES_FILE }}", mode: 0755}
    - {src: switch_config.py, dest: "{{ CLASH_SWITCH_CONFIG_FILE }}", mode: 0755}


- name: clash config files
  file:
    src: "{{ item.src }}"
    path: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - {src: clash, dest: "{{ CLASH_BIN_FILE }}", mode: 0755}
    - {src: Country.mmdb, dest: "{{ CLASH_COUNTRY_FILE }}", mode: 0644}


- name: config cron for update subscribes
  command: 'cru a clash_update_subscribes "0 5 * * * {{ CLASH_UPDATE_SUBSCRIBES_FILE }}"'

- name: make sure cron worked after reboot
  lineinfile:
    line: 'cru a clash_update_subscribes "0 3 * * * {{ CLASH_UPDATE_SUBSCRIBES_FILE }}"'
    path: "{{ JFFS_WAN_START_FILE }}"

