---

- name: make sure required jffs event files exist
  template:
    src: jffs_event.j2
    dest: "{{item}}"
    force: no
    mode: 0777
  loop:
    - "{{ JFFS_POST_MOUNT_FILE }}"
    - "{{ JFFS_WAN_START_FILE }}"
    - "{{ JFFS_DHCPC_EVENT_FILE }}"

- name: create config directory
  file:
    name: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ COMMON_ROOT_DIR }}"
    - "{{ COMMON_CFG_DIR }}"
    - "{{ COMMON_INITD_DIR }}"
    - "{{ COMMON_BIN_DIR }}"
    - "{{ COMMON_TMP_DIR }}"


- name: install packages
  opkg:
    name: "{{ item }}"
  loop:
    - python3
    - python3-yaml
