---

- name: create config directory
  file:
    name: "{{ item }}"
    state: directory
    mode: 0644
  loop:
    - "{{ DNSMASQ_CFG_DIR }}"
    - "{{ DNSMASQ_EXTRA_CFG_DIR }}"

- name: setup config file
  template:
    src: dnsmasq.conf.j2
    dest: "{{ DNSMASQ_CFG_FILE }}"

- name: setup init.d service file
  template:
    src: S08dnsmasq.j2
    dest: "{{ DNSMASQ_INITD_FILE }}"
    mode: 0755


- name: setup extra rules for dnsmasq
  template:
    src: through_dns2socks.conf.j2
    dest: "{{ DNSMASQ_EXTRA_CFG_DIR }}/through_dns2socks.conf"

- name: setup script for update whitelist
  template:
    src: update_whitelist.py.j2
    dest: "{{ DNSMASQ_UPDATE_WHITELIST_FILE }}"
    mode: 0755

- name: add cron for update whitelist
  command: 'cru a dnsmasq_update_whitelist "0 5 * * 0 {{ DNSMASQ_UPDATE_WHITELIST_FILE }}"'

- name: make sure cron works after reboot
  lineinfile:
    line: 'cru a dnsmasq_update_whitelist "0 5 * * 0 {{ DNSMASQ_UPDATE_WHITELIST_FILE }}"'
    path: "{{ JFFS_WAN_START_FILE }}"

- name: update whitelist
  command: "{{ DNSMASQ_UPDATE_WHITELIST_FILE }}"

- name: make sure dnsmasq restarted
  command: "{{ DNSMASQ_INITD_FILE }} restart"
